apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapp-backend-config
  namespace: taskapp
  labels:
    app: taskapp-backend
data:
  PORT: "5000"
  WORKERS: "4"
  CORS_ORIGINS: "https://myapp.api.euclaseresources.com"
  FLASK_ENV: production
  FLASK_DEBUG: "0"
