apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskapp-ingress
  namespace: taskapp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - taskapp.euclaseresources.com
        - api.euclaseresources.com
      secretName: taskapp-tls
  rules:
    - host: taskapp.euclaseresources.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskapp-frontend
                port:
                  number: 80
    - host: api.euclaseresources.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskapp-backend
                port:
                  number: 5000
