apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskapp
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - clusterissuer.yaml
  - ingress.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/lasglowtech/taskapp-backend
    newTag: f8467a7664c951639b792e35b699e1c1fbbeef60
  - name: ghcr.io/lasglowtech/taskapp-frontend
    newTag: f8467a7664c951639b792e35b699e1c1fbbeef60
