apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskapp
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/lasglowtech/taskapp-backend
    newTag: 0.1.0
  - name: ghcr.io/lasglowtech/taskapp-frontend
    newTag: 0.1.0
