apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskapp
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/lasglowtech/taskapp-backend
    newTag: b9ad734f13b9624aac9e365f2b8d13a6d4ed50d9
  - name: ghcr.io/lasglowtech/taskapp-frontend
    newTag: b9ad734f13b9624aac9e365f2b8d13a6d4ed50d9
