
apiVersion: v1
kind: Secret
metadata:
  name: taskapp-postgres-secret
  namespace: taskapp
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: "taskapp"
  POSTGRES_USER: "taskapp_admin"
  POSTGRES_PASSWORD: "52iCy9IZhesCWaT8PJ/KPmGnSXVQ7pDdOaW3X2RS2q8="
