frontend_app_dir: '{{app_base_dir}}/frontend'
frontend_branch: main
frontend_build_dir: '{{ frontend_source_dir }}/dist'
frontend_listen_port: 80
frontend_nginx_root: /var/www/taskapp
frontend_packages:
- nginx
frontend_repo_url: https://github.com/LASGLOWTECH/taskapp-frontend
frontend_source_dir: '{{app_base_dir}}/frontend'
frontend_src_dir: '{{ frontend_source_dir }}'
web_server_packages: nginx
