# packages required for front and backend.

common_packages:
  - wget
  - curl
  - git
  - ca-certificates
  - acl
  - gnupg 
  - python3-pip
  - python3-venv

app_user: taskapp
app_group: taskapp
app_base_dir: /opt/taskapp
